# 使用机器学习库scikit-learn 中的Iris 数据库，选取其中的第2-3 个特征，用KNN 进行Iris 花的分类。对数据标准化后，采用交叉验证方式，随机选择30%的数据作为测试集，进行测试，计算测试集上的平均准确率。

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report,confusion_matrix

# 加载数据
iris = datasets.load_iris()
X = iris.data[:, 1:3]
y = iris.target

# 数据标准化
scaler = StandardScaler()

X = scaler.fit_transform(X)

# 划分数据集
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

# 训练模型
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

# 预测
y_pred = knn.predict(X_test)

# 准确率
accuracy = accuracy_score(y_test, y_pred)
print('准确率：', accuracy)

# 混淆矩阵
print('混淆矩阵：')
print(confusion_matrix(y_test, y_pred))

# 分类报告
print('分类报告：')
print(classification_report(y_test, y_pred))

准确率： 0.9333333333333333
混淆矩阵：
[[13  1  0]
 [ 0 16  0]
 [ 0  2 13]]
分类报告：
              precision    recall  f1-score   support

           0       1.00      0.93      0.96        14
           1       0.84      1.00      0.91        16
           2       1.00      0.87      0.93        15

    accuracy                           0.93        45
   macro avg       0.95      0.93      0.94        45
weighted avg       0.94      0.93      0.93        45

