# 使用KNN完成简单手写数字识别系统

In [3]:
import numpy as np
import pandas as pd
import operator
from os import listdir
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report,confusion_matrix

# 将32*32的二进制图像转换为1*1024向量

def img2vector(filename):
    returnVect = np.zeros((1, 1024))
    fr = open(filename)
    for i in range(32):
        lineStr=fr.readline()
        for j in range(32):
            returnVect[0,32*i+j]=int(lineStr[j])
    return returnVect

hwLabels=[]
testLabels=[]
trainingFileList=listdir('C:/Users/Admin/Desktop/WHU study/programming/python/MachineLearning/exp1/digits/trainingDigits')
m=len(trainingFileList)
trainingMat=np.zeros((m,1024))
for i in range(m):
    fileNameStr=trainingFileList[i]
    fileStr=fileNameStr.split('.')[0]
    classNumStr=int(fileStr.split('_')[0])
    hwLabels.append(classNumStr)
    trainingMat[i,:]=img2vector('C:/Users/Admin/Desktop/WHU study/programming/python/MachineLearning/exp1/digits/trainingDigits/%s' % fileNameStr)
testFileList=listdir('C:/Users/Admin/Desktop/WHU study/programming/python/MachineLearning/exp1/digits/testDigits')
errorCount=0.0
mTest=len(testFileList)
vectorUnderTest=np.zeros((mTest,1024))
for i in range(mTest):
    fileNameStr=testFileList[i]
    fileStr=fileNameStr.split('.')[0]
    classNumStr=int(fileStr.split('_')[0])
    testLabels.append(classNumStr)
    vectorUnderTest[i,:]=img2vector('C:/Users/Admin/Desktop/WHU study/programming/python/MachineLearning/exp1/digits/testDigits/%s' % fileNameStr)
    
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(trainingMat,hwLabels)
    
y_pred = knn.predict(vectorUnderTest)

# 评估
print(confusion_matrix(testLabels, y_pred))
print(classification_report(testLabels, y_pred))

[[ 87   0   0   0   0   0   0   0   0   0]
 [  0  96   0   0   0   0   0   1   0   0]
 [  0   0  92   0   0   0   0   0   0   0]
 [  0   0   0  84   0   0   0   0   0   1]
 [  0   0   0   0 114   0   0   0   0   0]
 [  0   0   0   1   0 106   1   0   0   0]
 [  0   0   0   0   0   0  87   0   0   0]
 [  0   0   0   0   0   0   0  96   0   0]
 [  0   3   0   1   0   0   1   0  86   0]
 [  0   1   0   0   0   1   0   1   0  86]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        87
           1       0.96      0.99      0.97        97
           2       1.00      1.00      1.00        92
           3       0.98      0.99      0.98        85
           4       1.00      1.00      1.00       114
           5       0.99      0.98      0.99       108
           6       0.98      1.00      0.99        87
           7       0.98      1.00      0.99        96
           8       1.00      0.95      0.97        91
           9       0.99     