# 使用机器学习库scikit-learn 中的Iris 数据库，选取其中的第2-3 个特征，用KNN 进行Iris 花的分类。对数据标准化后，采用交叉验证方式，随机选择30%的数据作为测试集，进行测试，计算测试集上的平均准确率。

In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report,confusion_matrix

iris = datasets.load_iris()
X = iris.data[:, 2:4]
y = iris.target

# print(X)

scaler = StandardScaler()
X = scaler.fit_transform(X)
knn = KNeighborsClassifier(n_neighbors=3)
cnt=0
for i in range(100):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    cnt=cnt+accuracy

print('准确率：', cnt/100)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

准确率： 0.9553333333333316
[[16  0  0]
 [ 0 15  1]
 [ 0  0 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.94      0.97        16
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

