使用horseColicTraining.txt 文件作为训练集（每行包含了病马的20
个特征和是否死亡的标签），horseColicTest.txt 作为测试集，利用
Logistic回归预测病马的死亡率。计算多次迭代后的平均错误率。

In [21]:
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt
from numba.cpython.builtins import max_iterable
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report,confusion_matrix

dataTrain=pd.read_csv('C:/Users/Admin/Desktop/WHU study/programming/python/MachineLearning/exp2/horseColicTraining.txt', sep='\t', header=None)
dataTest=pd.read_csv('C:/Users/Admin/Desktop/WHU study/programming/python/MachineLearning/exp2/horseColicTest.txt', sep='\t', header=None)

def sigmoid(x):
    if x>=0:
        return 1.0/(1+np.exp(-x))
    else:
        return np.exp(x)/(1+np.exp(x))

def gradascent(dataMatrix, classLabels):
    dataMatrix=np.mat(dataMatrix)
    labelMat=np.mat(classLabels).transpose()
    m,n=np.shape(dataMatrix)
    alpha=0.001
    maxCycles=500
    weights=np.ones((n,1))
    for k in range(maxCycles):
        h=sigmoid(dataMatrix*weights)
        error=(labelMat-h)
        weights=weights+alpha*dataMatrix.transpose()*error# errormay
    return weights

def stocGradAscent(dataMatrix,classLabels,numIter=200):
    m,n=np.shape(dataMatrix)
    weights=np.ones(n)
    for j in range(numIter):
        dataIndex=list(range(m))
        for i in range(m):
            alpha=4/(1.0+j+i)+0.01
            randIndex=int(np.random.uniform(0,len(dataIndex)))
            h=sigmoid(sum(dataMatrix[randIndex]*weights))
            error=classLabels[randIndex]-h
            weights=weights+alpha*error*dataMatrix[randIndex]
            del(dataIndex[randIndex])
    return weights

def classifyVector(x,weights):
    prob=sigmoid(sum(x*weights))
    if prob>0.5:
        return 1.0
    else:
        return 0.0 

# print(dataTrain[dataTrain.columns[0:-1]])
weight=stocGradAscent(np.array(dataTrain[dataTrain.columns[0:-1]]),np.array(dataTrain[dataTrain.columns[-1]]))
print(weight)
y_pred=[]
# print(sum(np.mat(dataTest[dataTest.columns[0:-1]].iloc[0])*weight))
for i in range(len(dataTest)):
    y_pred.append(classifyVector(np.array(dataTest[dataTest.columns[0:-1]].iloc[i]),weight))
print(accuracy_score(dataTest[dataTest.columns[-1]],y_pred))
print(confusion_matrix(dataTest[dataTest.columns[-1]],y_pred))
print(classification_report(dataTest[dataTest.columns[-1]],y_pred))


[ 27.21383138  -2.49636655   4.22140456  -3.76728802   1.1920145
  -9.43434223  -0.31677144 -21.59025667 -13.5341711  -21.20437008
  40.53510745 -42.70384699  60.04510995  19.12441163 -26.70756053
   7.44465881  -5.84211943  -0.09262558  -0.74097668 -17.6552957
  -3.88531458]
0.5522388059701493
[[19  1]
 [29 18]]
              precision    recall  f1-score   support

           0       0.40      0.95      0.56        20
           1       0.95      0.38      0.55        47

    accuracy                           0.55        67
   macro avg       0.67      0.67      0.55        67
weighted avg       0.78      0.55      0.55        67



5.采用sklearn.linear_model.LogisticRegression实现上述数据集Logistic
回归预测病马死亡率。

In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report,confusion_matrix

dataTrain=pd.read_csv('C:/Users/Admin/Desktop/WHU study/programming/python/MachineLearning/exp2/horseColicTraining.txt', sep='\t', header=None).head()
dataTest=pd.read_csv('C:/Users/Admin/Desktop/WHU study/programming/python/MachineLearning/exp2/horseColicTest.txt', sep='\t', header=None).head()

model=LogisticRegression()
model.fit(dataTrain[dataTrain.columns[0:-1]],dataTrain[dataTrain.columns[-1]])
y_pred=model.predict(dataTest[dataTest.columns[0:-1]])
print(accuracy_score(dataTest[dataTest.columns[-1]],y_pred))
print(confusion_matrix(dataTest[dataTest.columns[-1]],y_pred))
print(classification_report(dataTest[dataTest.columns[-1]],y_pred))


0.8
[[1 0]
 [1 3]]
              precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       1.00      0.75      0.86         4

    accuracy                           0.80         5
   macro avg       0.75      0.88      0.76         5
weighted avg       0.90      0.80      0.82         5



通过访问：
http://archive.ics.uci.edu/ml/machine-learning-databases/horsecolic/
horse-colic.data 中提供的病马原始数据，采用sklearn.impute 中
SimpleImputer对原始缺失数据进行处理（处理策略不限定，如：特殊
值、均值等）。

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

data=pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/horse-colic/horse-colic.data',sep=' ')
data=data.replace('?',np.nan)
imp=SimpleImputer(strategy='median')
data=imp.fit_transform(data)
data=pd.DataFrame(data)
dataTrain,dataTest=train_test_split(data,test_size=0.2)
model=LogisticRegression(max_iter=10000)
model.fit(dataTrain[dataTrain.columns[0:-1]],dataTrain[dataTrain.columns[-1]])
y_pred=model.predict(dataTest[dataTest.columns[0:-1]])
print(accuracy_score(dataTest[dataTest.columns[-1]],y_pred))
print(confusion_matrix(dataTest[dataTest.columns[-1]],y_pred))
print(classification_report(dataTest[dataTest.columns[-1]],y_pred))


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\impute\_base.py:577: UserWarning: Skipping features without any observed values: ['2.4']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(


0.8333333333333334
[[ 6  7]
 [ 3 44]]
              precision    recall  f1-score   support

         1.0       0.67      0.46      0.55        13
         2.0       0.86      0.94      0.90        47

    accuracy                           0.83        60
   macro avg       0.76      0.70      0.72        60
weighted avg       0.82      0.83      0.82        60

