使用horseColicTraining.txt 文件作为训练集（每行包含了病马的20
个特征和是否死亡的标签），horseColicTest.txt 作为测试集，利用
Logistic回归预测病马的死亡率。计算多次迭代后的平均错误率。

In [4]:
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt
from numba.cpython.builtins import max_iterable
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report,confusion_matrix

dataTrain=pd.read_csv('C:/Users/Admin/Desktop/WHU study/programming/python/MachineLearning/exp2/horseColicTraining.txt', sep='\t', header=None)
dataTest=pd.read_csv('C:/Users/Admin/Desktop/WHU study/programming/python/MachineLearning/exp2/horseColicTest.txt', sep='\t', header=None)

def sigmoid(x):
    if x>=0:
        return 1.0/(1+np.exp(-x))
    else:
        return np.exp(x)/(1+np.exp(x))

def gradascent(dataMatrix, classLabels):
    dataMatrix=np.mat(dataMatrix)
    labelMat=np.mat(classLabels).transpose()
    m,n=np.shape(dataMatrix)
    alpha=0.001
    maxCycles=500
    weights=np.ones((n,1))
    for k in range(maxCycles):
        h=sigmoid(dataMatrix*weights)
        error=(labelMat-h)
        weights=weights+alpha*dataMatrix.transpose()*error# errormay
    return weights

def stocGradAscent(dataMatrix,classLabels,numIter=200):
    m,n=np.shape(dataMatrix)
    weights=np.ones(n)
    for j in range(numIter):
        dataIndex=list(range(m))
        for i in range(m):
            alpha=4/(1.0+j+i)+0.01
            randIndex=int(np.random.uniform(0,len(dataIndex)))
            h=sigmoid(sum(dataMatrix[randIndex]*weights))
            error=classLabels[randIndex]-h
            weights=weights+alpha*error*dataMatrix[randIndex]
            del(dataIndex[randIndex])
    return weights

def classifyVector(x,weights):
    prob=sigmoid(sum(x*weights))
    if prob>0.5:
        return 1.0
    else:
        return 0.0 

# print(dataTrain[dataTrain.columns[0:-1]])
weight=stocGradAscent(np.array(dataTrain[dataTrain.columns[0:-1]]),np.array(dataTrain[dataTrain.columns[-1]]))
print(weight)
y_pred=[]
# print(sum(np.mat(dataTest[dataTest.columns[0:-1]].iloc[0])*weight))
for i in range(len(dataTest)):
    y_pred.append(classifyVector(np.array(dataTest[dataTest.columns[0:-1]].iloc[i]),weight))
print(accuracy_score(dataTest[dataTest.columns[-1]],y_pred))
print(confusion_matrix(dataTest[dataTest.columns[-1]],y_pred))
print(classification_report(dataTest[dataTest.columns[-1]],y_pred))

error_rate=[]
for i in range(100):
    weight=stocGradAscent(np.array(dataTrain[dataTrain.columns[0:-1]]),np.array(dataTrain[dataTrain.columns[-1]]))
    y_pred=[]
    for j in range(len(dataTest)):
        y_pred.append(classifyVector(np.array(dataTest[dataTest.columns[0:-1]].iloc[j]),weight))
    error_rate.append(1-accuracy_score(dataTest[dataTest.columns[-1]],y_pred))
    
print(np.mean(error_rate))


[ 24.93947515  -4.07612611   4.14354925  -3.53393903   2.97848016
  -9.86649833  -1.1182112  -19.59087337  -7.50475604 -20.6928954
  43.21792789 -46.44507533  55.8787422   19.9962685  -30.00178965
   8.21021646  -4.8978743    0.44590411   0.27392694 -16.96728392
  -5.80955553]
0.6268656716417911
[[17  3]
 [22 25]]
              precision    recall  f1-score   support

           0       0.44      0.85      0.58        20
           1       0.89      0.53      0.67        47

    accuracy                           0.63        67
   macro avg       0.66      0.69      0.62        67
weighted avg       0.76      0.63      0.64        67

0.36970149253731344


5.采用sklearn.linear_model.LogisticRegression实现上述数据集Logistic
回归预测病马死亡率。

In [27]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report,confusion_matrix

dataTrain=pd.read_csv('C:/Users/Admin/Desktop/WHU study/programming/python/MachineLearning/exp2/horseColicTraining.txt', sep='\t', header=None)
dataTest=pd.read_csv('C:/Users/Admin/Desktop/WHU study/programming/python/MachineLearning/exp2/horseColicTest.txt', sep='\t', header=None)

model=LogisticRegression(max_iter=10000)
model.fit(dataTrain[dataTrain.columns[0:-1]],dataTrain[dataTrain.columns[-1]])
y_pred=model.predict(dataTest[dataTest.columns[0:-1]])
print(accuracy_score(dataTest[dataTest.columns[-1]],y_pred))
print(confusion_matrix(dataTest[dataTest.columns[-1]],y_pred))
print(classification_report(dataTest[dataTest.columns[-1]],y_pred))


0.7164179104477612
[[12  8]
 [11 36]]
              precision    recall  f1-score   support

           0       0.52      0.60      0.56        20
           1       0.82      0.77      0.79        47

    accuracy                           0.72        67
   macro avg       0.67      0.68      0.67        67
weighted avg       0.73      0.72      0.72        67



通过访问：
http://archive.ics.uci.edu/ml/machine-learning-databases/horsecolic/
horse-colic.data 中提供的病马原始数据，采用sklearn.impute 中
SimpleImputer对原始缺失数据进行处理（处理策略不限定，如：特殊
值、均值等）。

In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

# data=pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/horse-colic/horse-colic.data',sep=' ',header=None)
data=pd.read_csv('C:/Users/Admin/Desktop/WHU study/programming/python/MachineLearning/exp2/horse-colic.data',sep=' +',header=None,engine='python')
data=data.replace('?',np.nan)
data.drop(data.iloc[:,23:28],axis=1,inplace=True)
data.drop(data.columns[2],axis=1,inplace=True)
# imp=SimpleImputer(strategy='median')
imp=SimpleImputer(strategy='constant',fill_value='0')
data=imp.fit_transform(data)
data=pd.DataFrame(data).astype('float64')
dataTrain,dataTest=train_test_split(data,test_size=0.2)
model=LogisticRegression(max_iter=10000)
model.fit(dataTrain[dataTrain.columns[0:-1]],dataTrain[dataTrain.columns[-1]])
y_pred=model.predict(dataTest[dataTest.columns[0:-1]])
print(accuracy_score(dataTest[dataTest.columns[-1]],y_pred))
print(confusion_matrix(dataTest[dataTest.columns[-1]],y_pred))
print(classification_report(dataTest[dataTest.columns[-1]],y_pred,zero_division=1))


0.6833333333333333
[[31  5  1]
 [ 5  9  0]
 [ 7  1  1]]
              precision    recall  f1-score   support

         1.0       0.72      0.84      0.78        37
         2.0       0.60      0.64      0.62        14
         3.0       0.50      0.11      0.18         9

    accuracy                           0.68        60
   macro avg       0.61      0.53      0.53        60
weighted avg       0.66      0.68      0.65        60

